# Generated by Django 2.2.10 on 2021-07-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='title',
        ),
    ]
