# Generated by Django 2.2.10 on 2021-07-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0003_auto_20210706_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_answer', to='oprosnik.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_question', to='oprosnik.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_survey', to='oprosnik.Survey')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
